flags: {}
extra-package-dbs: []
packages:
- '.'
extra-deps:
- Glob-0.7.11
- HUnit-1.3.1.1
- SHA-1.6.4.2
- StateVar-1.1.0.4
- abstract-deque-0.3
- abstract-par-0.3.3
- adjunctions-4.3
- aeson-0.11.2.0
- ansi-terminal-0.6.2.3
- ansi-wl-pprint-0.6.7.3
- attoparsec-0.13.0.2
- base-orphans-0.5.4
- base64-bytestring-1.0.0.1
- bifunctors-5.4.1
- blaze-builder-0.4.0.2
- blaze-html-0.8.1.2
- blaze-markup-0.7.1.0
- byteable-0.1.1
- bytestring-builder-0.10.8.1.0
- case-insensitive-1.2.0.7
- cassava-0.4.5.0
- cereal-0.5.3.0
- cipher-aes-0.2.11
- clientsession-0.9.1.2
- clock-0.7.2
- comonad-5
- configurator-0.3.0.0
- contravariant-1.4
- cpphs-1.20.1
- cprng-aes-0.6.1
- criterion-1.1.1.0
- crypto-api-0.13.2
- crypto-cipher-types-0.0.9
- crypto-random-0.0.9
- cryptohash-0.11.9
- cryptonite-0.19
- directory-tree-0.12.0
- distributive-0.5.0.2
- dlist-0.8.0.1
- entropy-0.3.7
- erf-2.0.0.0
- errors-2.1.2
- exceptions-0.8.3
- extensible-exceptions-0.1.1.4
- fail-4.9.0.0
- free-4.12.4
- hashable-1.2.4.0
- haskell-src-exts-1.17.1
- haskell-src-meta-0.6.0.14
- hastache-0.6.1
- heist-1.0.0.0
- hostname-1.0
- ieee754-0.7.8
- io-streams-1.3.5.0
- io-streams-haproxy-1.0.0.1
- kan-extensions-5.0.1
- lens-4.14
- lifted-base-0.2.3.8
- map-syntax-0.2.0.1
- math-functions-0.2.0.1
- memory-0.13
- monad-control-1.0.1.0
- monad-par-0.3.4.8
- monad-par-extras-0.3.3
- mtl-2.2.1
- mwc-random-0.13.4.0
- network-2.6.3.1
- old-locale-1.0.0.7
- old-time-1.1.0.3
- optparse-applicative-0.12.1.0
- parallel-3.2.1.0
- parsec-3.1.11
- polyparse-1.12
- prelude-extras-0.4.0.3
- primitive-0.6.1.0
- profunctors-5.2
- pwstore-fast-2.4.4
- random-1.1
- readable-0.3.1
- reflection-2.1.2
- regex-base-0.93.2
- regex-posix-0.95.2
- safe-0.3.9
- scientific-0.3.4.9
- securemem-0.1.9
- semigroupoids-5.1
- semigroups-0.18.2
- setenv-0.1.1.3
- skein-1.0.9.4
- snap-1.0.0.0
- snap-core-1.0.0.0
- snap-server-1.0.0.0
- statistics-0.13.3.0
- stm-2.4.4.1
- syb-0.6
- tagged-0.8.5
- test-framework-0.8.1.1
- test-framework-hunit-0.3.0.2
- text-1.2.2.0
- th-expand-syns-0.4.0.0
- th-lift-0.7.6
- th-lift-instances-0.1.10
- th-orphans-0.13.2
- th-reify-many-0.1.6
- transformers-base-0.4.4
- transformers-compat-0.5.1.4
- unexceptionalio-0.3.0
- unix-compat-0.4.2.0
- unordered-containers-0.2.7.1
- vector-0.11.0.0
- vector-algorithms-0.7.0.1
- vector-binary-instances-0.2.3.2
- vector-th-unbox-0.2.1.6
- void-0.7.1
- websockets-0.9.7.0
- websockets-snap-0.10.0.0
- xml-1.3.14
- xmlhtml-0.2.3.5
- zlib-0.6.1.1
- zlib-bindings-0.1.1.5
resolver: ghc-8.0.1
